edition="2021"

max_width=100

comment_width = 100
wrap_comments = true

condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true
