[package]
name = "problemdetails-example-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
problemdetails = { path = "../..", features = ["axum"] }

axum = { version = "0.5.11"}
http = "0.2.8"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
tokio = { version = "1.0", features = ["full"] }

